import 'package:multi_dropdown/models/value_item.dart';

List<ValueItem> categorylist = [
  ValueItem(label: 'TFWS', value: '1'),
  ValueItem(label: 'LOPENS', value: '2'),
  ValueItem(label: 'GOPENS', value: '3'),
  ValueItem(label: 'GNT3S', value: '4'),
  ValueItem(label: 'LNT2S', value: '5'),
  ValueItem(label: 'GNT2S', value: '6'),
  ValueItem(label: 'GOBCS', value: '7'),
  ValueItem(label: 'EWS', value: '8'),
  ValueItem(label: 'LOBCS', value: '9'),
  ValueItem(label: 'LNT1S', value: '10'),
  ValueItem(label: 'DEFOPENS', value: '11'),
  ValueItem(label: 'DEFROBCS', value: '12'),
  ValueItem(label: 'GOPENO', value: '13'),
  ValueItem(label: 'LOPENO', value: '14'),
  ValueItem(label: 'GOPENH', value: '15'),
  ValueItem(label: 'GNT2O', value: '16'),
  ValueItem(label: 'GOBCO', value: '17'),
  ValueItem(label: 'GNT1S', value: '18'),
  ValueItem(label: 'GVJS', value: '19'),
  ValueItem(label: 'DEFOBCS', value: '20'),
  ValueItem(label: 'ORPHAN', value: '21'),
  ValueItem(label: 'LOPENH', value: '22'),
  ValueItem(label: 'GNT3H', value: '23'),
  ValueItem(label: 'LNT3S', value: '24'),
  ValueItem(label: 'GOBCH', value: '25'),
  ValueItem(label: 'LNT1H', value: '26'),
  ValueItem(label: 'LSCS', value: '27'),
  ValueItem(label: 'LNT2H', value: '28'),
  ValueItem(label: 'LNT3H', value: '29'),
  ValueItem(label: 'GNT1H', value: '30'),
  ValueItem(label: 'LOBCO', value: '31'),
  ValueItem(label: 'GNT1O', value: '32'),
  ValueItem(label: 'LOBCH', value: '33'),
  ValueItem(label: 'AI', value: '34'),
  ValueItem(label: 'GSCS', value: '35'),
  ValueItem(label: 'LVJS', value: '36'),
  ValueItem(label: 'LVJH', value: '37'),
  ValueItem(label: 'GNT3O', value: '38'),
  ValueItem(label: 'PWDOPENS', value: '39'),
  ValueItem(label: 'GNT2H', value: '40'),
  ValueItem(label: 'LNT2O', value: '41'),
  ValueItem(label: 'GVJO', value: '42'),
  ValueItem(label: 'GSCO', value: '43'),
  ValueItem(label: 'LSCO', value: '44'),
  ValueItem(label: 'DEFRNT2S', value: '45'),
  ValueItem(label: 'MI', value: '46'),
  ValueItem(label: 'GSCH', value: '47'),
  ValueItem(label: 'PWDOBCS', value: '48'),
  ValueItem(label: 'MI-MH', value: '49'),
  ValueItem(label: 'GVJH', value: '50'),
  ValueItem(label: 'PWDOPE..', value: '51'),
  ValueItem(label: 'DEFOPCS', value: '52'),
  ValueItem(label: 'PWDSCS', value: '53'),
  ValueItem(label: 'GSTS', value: '54'),
  ValueItem(label: 'DEFRNT3S', value: '55'),
  ValueItem(label: 'PWDOPENH', value: '56'),
  ValueItem(label: 'LSTS', value: '57'),
  ValueItem(label: 'DEFRSCS', value: '58'),
  ValueItem(label: 'PWDROBCS', value: '59'),
  ValueItem(label: 'LSCH', value: '60'),
  ValueItem(label: 'PWDOBCH', value: '61')
];

List<ValueItem> citylist = [
  ValueItem(label: 'Mumbai', value: '1'),
  ValueItem(label: 'Pune', value: '2'),
  ValueItem(label: 'Sangli', value: '3'),
  ValueItem(label: 'Mumba', value: '4'),
  ValueItem(label: 'Nagpur', value: '5'),
  ValueItem(label: 'Aurangabad', value: '6'),
  ValueItem(label: 'Karad', value: '7'),
  ValueItem(label: 'Navi Mumbai', value: '8'),
  ValueItem(label: 'Nanded', value: '9'),
  ValueItem(label: 'Kolhapur', value: '10'),
  ValueItem(label: 'Amravati', value: '11'),
  ValueItem(label: 'Avasari Khurd', value: '12'),
  ValueItem(label: 'Andheri', value: '13'),
  ValueItem(label: 'Nashik', value: '14'),
  ValueItem(label: 'Shegaon', value: '15'),
  ValueItem(label: 'Ichalkaranji', value: '16'),
  ValueItem(label: 'Sangamner', value: '17'),
];

List<ValueItem> branchlist = [
  ValueItem(label: 'Computer Engineering', value: '1'),
  ValueItem(label: 'Information Technology', value: '2'),
  ValueItem(label: 'Electronics and Telecommunication Engineering', value: '3'),
  ValueItem(label: 'Computer Science and Engineering (AI and ML)', value: '4'),
  ValueItem(label: 'Computer Science and Engineering (Data Science)', value: '5'),
  ValueItem(label: 'Computer Science and Engineering', value: '6'),
  ValueItem(label: 'Electrical Engineering', value: '7'),
  ValueItem(label: 'Chemical Engineering', value: '8'),
  ValueItem(label: 'Electronics Engineering', value: '9'),
  ValueItem(label: 'Instrumentation and Control Engineering', value: '10'),
  ValueItem(label: 'Mechanical Engineering', value: '11'),
  ValueItem(label: 'Artificial Intelligence (AI) and Data Science', value: '12'),
  ValueItem(label: 'Computer Science and Engineering (AI)', value: '13'),
  ValueItem(label: 'Polymer Engineering and Technology', value: '14'),
  ValueItem(label: 'Pharmaceuticals Chemistry and Technology', value: '15'),
  ValueItem(label: 'Computer Science and Engineering (Internet of Things and Cyber Security Including Block Chain Technology)', value: '16'),
  ValueItem(label: 'Civil Engineering', value: '17'),
  ValueItem(label: 'Food Engineering and Technology', value: '18'),
  ValueItem(label: 'Computer Science and Engineering(Data Science)', value: '19'),
  ValueItem(label: 'Artificial Intelligence and Data Science', value: '20'),
  ValueItem(label: 'Electronics and Telecommunication Engg', value: '21'),
  ValueItem(label: 'Computer Science and Engineering (Artificial Intelligence)', value: '22'),
  ValueItem(label: 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)', value: '23'),
  ValueItem(label: 'Artificial Intelligence and Machine Learning', value: '24'),
  ValueItem(label: 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)', value: '25'),
  ValueItem(label: 'Computer Engineering (Regional Language)', value: '26'),
  ValueItem(label: 'Manufacturing Science and Engineering', value: '27'),
  ValueItem(label: 'Oil,Oleochemicals and Surfactants Technology', value: '28'),
  ValueItem(label: 'Surface Coating Technology', value: '29'),
  ValueItem(label: 'Production Engineering[Sandwich]', value: '30'),
  ValueItem(label: 'Oil, Oleochemicals and Surfactants Technology', value: '31'),
  ValueItem(label: 'Computer Science and Business Systems', value: '32'),
  ValueItem(label: 'Metallurgy and Material Technology', value: '33'),
  ValueItem(label: 'Computer Science and Information Technology', value: '34'),
  ValueItem(label: 'Computer Science and Engineering(Cyber Security)', value: '35'),
];