// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKnHyVOUrqSsqm6C3jEeVzrDPp4Sdb31k',
    appId: '1:598475931298:android:69e6e150fb89bf0cfce1fb',
    messagingSenderId: '598475931298',
    projectId: 'find-my-college-c70be',
    databaseURL: 'https://find-my-college-c70be-default-rtdb.firebaseio.com',
    storageBucket: 'find-my-college-c70be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp5971KsghC9guhYmlz893SVUyjeZUQy4',
    appId: '1:598475931298:ios:384b991d896e297efce1fb',
    messagingSenderId: '598475931298',
    projectId: 'find-my-college-c70be',
    databaseURL: 'https://find-my-college-c70be-default-rtdb.firebaseio.com',
    storageBucket: 'find-my-college-c70be.appspot.com',
    iosBundleId: 'com.example.findMyCollege',
  );
}
